version: '3.8'

services:
  postgres:
    container_name: lumi-pg
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: lumi
      POSTGRES_PASSWORD: lumi
      POSTGRES_DB: lumi
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
